#!/bin/sh
# This script pings a given IPv4 address a given amount of times on an
# interface(s) which is a default route. Depending on the average round-trip
# time, it makes the affine subflow a backup or not a backup.
# Author: Chester A. Unal <chester.a.unal@arinc9.com>
# Author: Dwayne Du Preez <dwayne.dupreez@xpedite-tech.com>

TIMEOUT_MS=900
COUNT=1
SERVER_IP=8.8.8.8
INTERVAL=1
WINDOW_SIZE=100
THRESHOLD_PERCENT=5
SUBFLOW_LIMIT=8

# Adjust MPTCP subflow limit.
ip mp limits set subflows "$SUBFLOW_LIMIT"

while true; do
	sleep "$INTERVAL"

	# Get all default routes with a metric.
	routes=$(ip route show | grep "^default" | grep "metric")

	# Count the number of routes.
	route_count=$(echo "$routes" | grep -c "metric")

	# Continue if there are less than two routes.
	[ "$route_count" -lt 2 ] && continue

	# Extract interfaces from default routes.
	interfaces=$(echo "$routes" | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}')

	awk_output=$(
	for IFACE in $interfaces; do
		# If interface is declared backup and its endpoint is nobackup,
		# set it backup and continue for declared backup interface.
		ENDPOINTS=$(ip mp e)
		if uci -q get bsbf-mptcp.main.subflow_backup | grep -q "$IFACE"; then
			if echo "$ENDPOINTS" | grep -q "dev $IFACE" && \
			   ! echo "$ENDPOINTS" | grep "dev $IFACE" | grep -q "backup"; then
				bsbf-mptcp-helper backup "$IFACE"
			fi
			continue
		fi

		# Run fping to get the average RTT of an interface.
		OUTPUT=$(fping -q -t "$TIMEOUT_MS" -c "$COUNT" -I "$IFACE" "$SERVER_IP" 2>&1)
		# Remove the interface if there's no connectivity and continue.
		[ "$?" -ne 0 ] && { bsbf-mptcp-helper remove "$IFACE" ; continue; }

		# Set isbackup if interface is a backup subflow. Otherwise, add
		# an mptcp endpoint for the interface if there isn't one for it.
		# If adding an mptcp endpoint fails, continue the loop so it
		# won't be fed to awk.
		isbackup=0
		if echo "$ENDPOINTS" | grep "dev $IFACE" | grep -q "backup"; then
			isbackup=1
		elif ! echo "$ENDPOINTS" | grep -q "dev $IFACE"; then
			bsbf-mptcp-helper add "$IFACE" || continue
		fi

		rtt=$(echo "$OUTPUT" | awk -F'/' '{print $8}')
		echo "$IFACE $rtt $isbackup"
	done
	)

	# Run awk if there are more than 1 interface.
	[ "$(echo "$awk_output" | wc -l)" -gt 1 ] && \
	echo "$awk_output" | awk -v w="$WINDOW_SIZE" threshold="$THRESHOLD_PERCENT" '
	{
		iface = $1; val = $2; isbackup = $3
		logfile = "/var/log/bsbf-mptcp.log"

		backup_str = (isbackup == 1 ? "Yes" : "No")
		ts = strftime("%Y-%m-%d %H:%M:%S", systime(), 1)
		print ts, iface, "is backup?:", backup_str >> logfile

		# Calculate Rolling Average
		idx[iface] = (idx[iface] % w) + 1
		sum[iface] -= hist[iface, idx[iface]]
		hist[iface, idx[iface]] = val
		sum[iface] += val
		if (count[iface] < w) count[iface]++
		avg = sum[iface] / count[iface]
		coefficient = ((1000 - avg) / 1000) * 100

		# 2. Find the BEST interface currently known
		best_coeff = -999
		best_iface = ""
		for (i in sum) {
			if (count[i] == 0) continue
			current_i_coeff = ((1000 - (sum[i]/count[i])) / 1000) * 100
			if (current_i_coeff > best_coeff) {
				best_coeff = current_i_coeff
				best_iface = i
			}
		}

		print ts, iface, "Avg RTT:", avg, "(Coeff:", coefficient "%)" >> logfile
		print ts, "Current Leader:", best_iface, "(Coeff:", best_coeff "%)" >> logfile

		# 3. Decision Logic
		if (iface != best_iface) {
			diff = best_coeff - coefficient
			print ts, iface, "is", diff "% worse than", best_iface >> logfile

			if (diff >= threshold && isbackup != 1) {
				print ts, "Triggering backup for", iface >> logfile
				system("logger -t bsbf-mptcp Triggering backup for " iface)
				system("bsbf-mptcp-helper backup " iface)
			}
			if (diff < threshold && isbackup == 1) {
				print ts, iface, "is now better. Restoring..." >> logfile
				system("logger -t bsbf-mptcp " iface " is now better. Restoring...")
				system("bsbf-mptcp-helper nobackup " iface)
			}
		} else {
			# This IS the best interface
			if (isbackup == 1) {
				print ts, iface, "is now the leader. Restoring..." >> logfile
				system("logger -t bsbf-mptcp " iface " is now the leader. Restoring...")
				system("bsbf-mptcp-helper nobackup " iface)
			}
		}

		fflush()
	}
	'
done
