#!/bin/sh
# This script sets up a network with a DHCP client for a CDC-ECM USB interface.
# This can be a cellular modem or an Ethernet to USB adapter.
# Author: Chester A. Unal <chester.a.unal@arinc9.com>

for IFACE in /sys/bus/usb/devices/*:*; do
	class=$(cat $IFACE/bInterfaceClass)
	subclass=$(cat $IFACE/bInterfaceSubClass)
	[ "$class" = "02" ] && [ "$subclass" = "06" ] || continue

	NETDEV="$(ls $IFACE/net)"
	uci set network.pluggable_modem=interface
	uci set network.pluggable_modem.device="$NETDEV"
	uci set network.pluggable_modem.proto='dhcp'
	uci set network.pluggable_modem.metric='9'
	uci set network.pluggable_modem.auto='0'
	uci commit network
	ifup pluggable_modem
done
