# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025-2026 Chester A. Unal <chester.a.unal@arinc9.com>

[Service]
ExecStart=
ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray-bsbf-bonding/config.json

ExecStartPost=/usr/sbin/ip rule add priority 0 fwmark 1 table 1
ExecStartPost=/usr/sbin/ip route add local default dev lo table 1
ExecStartPost=/usr/sbin/nft -f /etc/nftables/bsbf_bonding.nft

ExecStopPost=/usr/sbin/nft destroy table bsbf_bonding
ExecStopPost=/usr/sbin/ip route flush table 1
ExecStopPost=/usr/sbin/ip rule delete priority 0 fwmark 1 table 1
