#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025-2026 Chester A. Unal <chester.a.unal@arinc9.com>

if [ $# -ne 2 ] || { [ "$1" != "l2" ] && [ "$1" != "l3" ]; }; then
	echo "Usage: $0 l2|l3 <interface>"
	exit 1
fi

. /etc/bsbf/bsbf-bonding.conf

SEC="tc"
if [ "$1" = "l3" ]; then
	SEC="tc_l3"
fi

IFACE="$2"
PROGRAMME=/usr/lib/bpf/tcp_in_udp_tc.o

# Mark rule matches a packet if ((mark & MARK_MASK) == (MARK & MARK_MASK))
# is true. Mark is a 32-bit value.
MARK=0x2
# Set all bits so that a mark with only the value of MARK matches the rule.
MARK_MASK=0xffffffff

# Port rule matches a packet if ((port & PORT_MASK) == (PORT & PORT_MASK))
# is true. Port is a 16-bit value.
PORT="$server_port"
# Set all bits so that a port with only the value of PORT matches the rule.
PORT_MASK=0xffff

# IPv4 address of the server, optionally suffixed by a prefix length. Put in
# "any" to match any address.
IPv4="$server_ipv4"

# Disable GRO and GSO.
ethtool -K "$IFACE" gro off 2>/dev/null
ip link set "$IFACE" gso_max_segs 0

# (Re-)add the clsact queuing discipline, and add egress and ingress filters.
tc qdisc del dev "$IFACE" clsact 2>/dev/null
tc qdisc replace dev "$IFACE" clsact
tc filter add dev "$IFACE" egress u32 match mark "$MARK" "$MARK_MASK" action goto chain 1
tc filter add dev "$IFACE" egress chain 1 bpf object-file "$PROGRAMME" section "$SEC" action csum udp
tc filter add dev "$IFACE" ingress u32 match ip src "$IPv4" match ip sport "$PORT" "$PORT_MASK" action goto chain 1
tc filter add dev "$IFACE" ingress chain 1 bpf object-file "$PROGRAMME" section "$SEC"
