server.modules = ( "mod_cgi" )
server.document-root = "/srv/bsbf-client-web"
server.port = 8080
server.bind = "0.0.0.0"
index-file.names = ( "index.html" )
$HTTP["url"] =~ "^/cgi-bin/" { cgi.assign = ( "" => "" ) }
