#!/bin/sh
# This script loads the TCP-in-UDP BPF programme to a specified interface.
#
# Regarding matching packets for the TCP-in-UDP BPF programme, use fwmark for
# egress to prevent processing traffic that is not from the TCP programme. For
# client, this allows traffic to a different IP address with the same TCP port.
# For server, this prevents sending packet to BPF programme if the interface has
# multiple IP addresses assigned and if the TCP programme doesn't bind to all of
# them.
#
# Author: Chester A. Unal <chester.a.unal@arinc9.com>

if [ $# -ne 2 ] || { [ "$1" != "l2" ] && [ "$1" != "l3" ]; }; then
    echo "Usage: $0 l2|l3 <interface>"
    exit 1
fi

SEC="tc"
if [ "$1" = "l3" ]; then
    SEC="tc_l3"
fi

IFACE="$2"
PROGRAMME=/usr/local/share/tcp-in-udp/tcp_in_udp_tc.o

# Mark rule matches a packet if ((mark & MARK_MASK) == (BASE_MARK & MARK_MASK))
# is true. Mark is a 32-bit value.
# Value of bit 1 in hex. Bit 1 must be set on packet's mark.
BASE_MARK=0x2
# Set bits 31 to 0 on mask so that a mark with only bit 1 that is set (2)
# matches the rule.
MARK_MASK=0xffffffff

# Port rule matches a packet if ((port & PORT_MASK) == (BASE_PORT & PORT_MASK))
# is true. Port is a 16-bit value.
BASE_PORT=
# Set bits 15 to 0 on mask so that only the base port matches the rule.
PORT_MASK=0xffff

# IPv4 address of the server, optionally suffixed by a prefix length. Put in
# "any" to match any address.
IPv4=""

# Lowering MTU is necessary for UDP conversion to work. 1408 works on all ISPs
# so far.
ip link set "$IFACE" mtu 1408 && \
ethtool -K "$IFACE" gro off 2>/dev/null && \
ip link set "$IFACE" gso_max_segs 0 && \
tc qdisc del dev "$IFACE" clsact 2>/dev/null ; \
tc qdisc replace dev "$IFACE" clsact && \
tc filter add dev "$IFACE" egress u32 match mark "$BASE_MARK" "$MARK_MASK" action goto chain 1 && \
tc filter add dev "$IFACE" egress chain 1 bpf object-file "$PROGRAMME" section "$SEC" action csum udp && \
tc filter add dev "$IFACE" ingress u32 match ip src "$IPv4" match ip sport "$BASE_PORT" "$PORT_MASK" action goto chain 1 && \
tc filter add dev "$IFACE" ingress chain 1 bpf object-file "$PROGRAMME" section "$SEC" direct-action
