#!/bin/sh
# This script creates a network with a DHCP client using a newly created network
# interface. It uses metric values from 7 to 9.

# Only run if a network interface from a USB device is being added.
[ "$ACTION" = "add" ] && echo "$DEVPATH" | grep -q usb || exit

# Exclude wwan and qmimux network interfaces which a DHCP client wouldn't work
# on.
case "$DEVICENAME" in
	wwan*|qmimux*) exit ;;
esac

# Decide on the metric value. Start from 7 and work up to 9.
metric=7
while [ $metric -le 9 ]; do
	# Break if this metric isn't in use.
	uci show network | grep -q ".metric='$metric'" || break

	# Exit if this metric is in use for the same network interface.
	[ "$(uci get network.wan_"$DEVICENAME".metric)" = "$metric" ] && exit

	# Add 1 from metric if another network uses this metric.
	metric=$((metric + 1))
done

uci set network.wan_"$DEVICENAME"=interface
uci set network.wan_"$DEVICENAME".device="$DEVICENAME"
uci set network.wan_"$DEVICENAME".proto='dhcp'
uci set network.wan_"$DEVICENAME".peerdns='0'
uci set network.wan_"$DEVICENAME".metric="$metric"
uci commit network
ifup wan_"$DEVICENAME"
