#!/bin/sh
# This script pings a given IPv4 address a given amount of times on an
# interface(s) which is a default route. Depending on the average round-trip
# time, it makes the affine subflow a backup or not a backup.
# Author: Chester A. Unal <chester.a.unal@arinc9.com>
# Author: Dwayne Du Preez <dwayne.dupreez@xpedite-tech.com>

TIMEOUT_MS=900
COUNT=1
SERVER_IP=8.8.8.8
INTERVAL=0.3
W_SIZE=5

while true; do
	sleep "$INTERVAL"

	# Get all default routes with a metric.
	routes=$(ip route show | grep "^default" | grep "metric")

	# Count the number of routes.
	route_count=$(echo "$routes" | grep -c "metric")

	# Continue if there are less than two routes.
	[ "$route_count" -lt 2 ] && continue

	# Extract interfaces from default routes.
	interfaces=$(echo "$routes" | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}')

	for IFACE in $interfaces; do
		# Run fping to get the average RTT of an interface.
		OUTPUT=$(fping -q -t "$TIMEOUT_MS" -c "$COUNT" -I "$IFACE" "$SERVER_IP" 2>&1)
		# Make the interface a backup subflow if there's no connectivity and continue.
		[ "$?" -ne 0 ] && { bsbf-mptcp-helper backup "$IFACE" ; continue; }

		# Set isbackup if interface is a backup subflow.
		isbackup=$(ip mp e | grep -q "dev $IFACE" | grep -q "backup")

		rtt=$(echo "$OUTPUT" | awk -F'/' '{print $8}')
		echo "DATA $IFACE $rtt $isbackup"
	done | awk -v w="$W_SIZE" '

	$1 == "DATA" {
		iface = $2; val = $3
		isbackup = $4
		print "INFO: " iface " Is Backup?: " isbackup " Ifacename: " ifacename
		# Calculate Rolling Average
		idx[iface] = (idx[iface] % w) + 1
		sum[iface] -= hist[iface, idx[iface]]
		hist[iface, idx[iface]] = val
		sum[iface] += val
		if (count[iface] < w) count[iface]++
		avg = sum[iface] / count[iface]
		coefficient = ((1000 - avg) / 1000) * 100
		print "INFO: " iface " Avg RTT: " avg
		print "INFO: " iface " Coefficient: " coefficient

		# 2. Find the BEST interface currently known
		best_coeff = -999
		best_iface = ""
		for (i in sum) {
			if (count[i] == 0) continue
			current_i_coeff = ((1000 - (sum[i]/count[i])) / 1000) * 100
			if (current_i_coeff > best_coeff) {
				best_coeff = current_i_coeff
				best_iface = i
			}
		}

		print "INFO: " iface " Avg RTT: " avg " (Coeff: " coefficient "%)"
		print "INFO: Current Leader: " best_iface " (Coeff: " best_coeff "%)"

		# 3. Decision Logic
		if (iface != best_iface) {
			diff = best_coeff - coefficient
			print "INFO: " iface " is " diff "% worse than " best_iface

			if (diff > 5) {
				print "INFO: Triggering backup for " iface
				system("bsbf-mptcp-helper backup " iface)
			}
			if (diff < 5 && isbackup == 1) {
				print "INFO: " iface " is now better. Restoring..."
				system("bsbf-mptcp-helper nobackup " iface)
			}
		} else {
			# This IS the best interface
			if (isbackup == 1) {
				print "INFO: " iface " is now the leader. Restoring..."
				system("bsbf-mptcp-helper nobackup " iface)
			}
		}
	}

	{ fflush() }
	'
done
