#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chester A. Unal <chester.a.unal@arinc9.com>

find /usr/local/etc/xray-bsbf-bonding -maxdepth 1 -type f -name "[0-9]*-*.json" | sort -t- -k1 -n | while read -r FILE; do
	FILENAME=$(basename "$FILE" .json)
	PORT=${FILENAME%%-*}
	SPEED=${FILENAME##*-}
	UUID=${FILENAME#*-}
	UUID=${UUID%-*}
	echo "$PORT" "$UUID" "$SPEED"
done
